version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21

  pre_build:
    commands:
      - yarn install

  build:
    commands:
      - yarn build

artifacts:
  files:
    - "**/*"
  base-directory: dist